export const nigeriaStates = [
  { value: "abia", title: "Abia" },
  { value: "adamawa", title: "Adamawa" },
  { value: "akwa-ibom", title: "Akwa Ibom" },
  { value: "anambra", title: "Anambra" },
  { value: "bauchi", title: "Bauchi" },
  { value: "bayelsa", title: "Bayelsa" },
  { value: "benue", title: "Benue" },
  { value: "borno", title: "Borno" },
  { value: "cross-river", title: "Cross River" },
  { value: "delta", title: "Delta" },
  { value: "ebonyi", title: "Ebonyi" },
  { value: "edo", title: "Edo" },
  { value: "ekiti", title: "Ekiti" },
  { value: "enugu", title: "Enugu" },
  { value: "gombe", title: "Gombe" },
  { value: "imo", title: "Imo" },
  { value: "jigawa", title: "Jigawa" },
  { value: "kaduna", title: "Kaduna" },
  { value: "kano", title: "Kano" },
  { value: "katsina", title: "Katsina" },
  { value: "kebbi", title: "Kebbi" },
  { value: "kogi", title: "Kogi" },
  { value: "kwara", title: "Kwara" },
  { value: "lagos", title: "Lagos" },
  { value: "nasarawa", title: "Nasarawa" },
  { value: "niger", title: "Niger" },
  { value: "ogun", title: "Ogun" },
  { value: "ondo", title: "Ondo" },
  { value: "osun", title: "Osun" },
  { value: "oyo", title: "Oyo" },
  { value: "plateau", title: "Plateau" },
  { value: "rivers", title: "Rivers" },
  { value: "sokoto", title: "Sokoto" },
  { value: "taraba", title: "Taraba" },
  { value: "yobe", title: "Yobe" },
  { value: "zamfara", title: "Zamfara" },
  { value: "fct", title: "Federal Capital Territory" },
];
